 Generated by Django 3.1.1 on 2020-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
