 Generated by Django 3.1.1 on 2020-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0002_auto_20200930_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
