# Generated by Django 3.1.1 on 2020-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='phone',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
