# Generated by Django 3.1.1 on 2020-10-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0002_auto_20201001_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('task', 'candidate')},
        ),
    ]
