# Generated by Django 3.1.1 on 2020-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0004_auto_20201002_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grading.candidate'),
        ),
    ]
