# Generated by Django 3.1.1 on 2020-10-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grading', '0005_auto_20201002_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grading.recruiter'),
        ),
    ]
